In [3]:
!python --version

Python 3.13.9


In [4]:
import os
os.makedirs("alzheimers_project/data", exist_ok=True)
os.chdir("alzheimers_project")
print(os.getcwd())

C:\Users\Deepak\Downloads\Cap2_ML\Model\alzheimers_project


In [5]:
!pip install pandas numpy scikit-learn xgboost flask joblib kaggle

   ---------------------------------------- 0.0/48.9 MB ? eta -:--:--
   - -------------------------------------- 2.1/48.9 MB 11.6 MB/s eta 0:00:05
   --- ------------------------------------ 4.5/48.9 MB 11.7 MB/s eta 0:00:04
   ----- ---------------------------------- 6.8/48.9 MB 11.7 MB/s eta 0:00:04
   ------- -------------------------------- 9.2/48.9 MB 11.7 MB/s eta 0:00:04
   --------- ------------------------------ 11.5/48.9 MB 11.7 MB/s eta 0:00:04
   ----------- ---------------------------- 13.9/48.9 MB 11.7 MB/s eta 0:00:04
   ------------- -------------------------- 16.3/48.9 MB 11.7 MB/s eta 0:00:03
   --------------- ------------------------ 18.6/48.9 MB 11.7 MB/s eta 0:00:03
   ----------------- ---------------------- 21.0/48.9 MB 11.7 MB/s eta 0:00:03
   ------------------- -------------------- 23.3/48.9 MB 11.7 MB/s eta 0:00:03
   -------------------- ------------------- 25.7/48.9 MB 11.7 MB/s eta 0:00:02
   ---------------------- ----------------- 27.3/48.9 MB 11.7 MB/

In [6]:
#creating kaggle api t

import os, json

kaggle_dir = os.path.expanduser("~/.kaggle")
os.makedirs(kaggle_dir, exist_ok=True)

token = {
    "username": "deepaktarun23",
    "key": "KGAT_2acdf540c91e842368be9ffa07ab5e56"
}

path = os.path.join(kaggle_dir, "kaggle.json")
with open(path, "w") as f:
    json.dump(token, f)

print("Saved to:", path)

Saved to: C:\Users\Deepak/.kaggle\kaggle.json


In [7]:
!kaggle datasets list -s alzheimer

ref                                                               title                                                  size  lastUpdated                 downloadCount  voteCount  usabilityRating  
----------------------------------------------------------------  -----------------------------------------------  ----------  --------------------------  -------------  ---------  ---------------  
brsdincer/alzheimer-features                                      Alzheimer Features                                     4426  2021-03-30 19:38:20.697000           8026         98                1  
uraninjo/augmented-alzheimer-mri-dataset                          Augmented Alzheimer MRI Dataset                   398281659  2022-09-20 19:35:49.840000          25621        140            0.875  
b"rabieelkharoua/alzheimers-disease-dataset                         \xf0\x9f\xa7\xa0 Alzheimer's Disease Dataset \xf0\x9f\xa7\xa0                      274395  2024-06-11 20:24:30.613000          37040    

In [8]:
#downloading dataset

!kaggle datasets download -d rabieelkharoua/alzheimers-disease-dataset -p ./data --unzip

Dataset URL: https://www.kaggle.com/datasets/rabieelkharoua/alzheimers-disease-dataset
License(s): Attribution 4.0 International (CC BY 4.0)




  0%|          | 0.00/268k [00:00<?, ?B/s]
100%|##########| 268k/268k [00:00<00:00, 282kB/s]
100%|##########| 268k/268k [00:00<00:00, 281kB/s]


In [9]:
import os
print(os.listdir("data"))

['alzheimers_disease_data.csv']


In [11]:
#importing datasetimport pandas as pd

import pandas as pd

df = pd.read_csv("data/alzheimers_disease_data.csv")

print("Shape:", df.shape)
df.head()

Shape: (2149, 35)


,PatientID,Age,Gender,Ethnicity,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,DietQuality,...,MemoryComplaints,BehavioralProblems,ADL,Confusion,Disorientation,PersonalityChanges,DifficultyCompletingTasks,Forgetfulness,Diagnosis,DoctorInCharge
0,4751,73,0,0,2,22.927749,0,13.297218,6.327112,1.347214,...,0,0,1.725883,0,0,0,1,0,0,XXXConfid
1,4752,89,0,0,0,26.827681,0,4.542524,7.619885,0.518767,...,0,0,2.592424,0,0,0,0,1,0,XXXConfid
2,4753,73,0,3,1,17.795882,0,19.555085,7.844988,1.826335,...,0,0,7.119548,0,1,0,1,0,0,XXXConfid
3,4754,74,1,0,1,33.800817,1,12.209266,8.428001,7.435604,...,0,1,6.481226,0,0,0,0,0,0,XXXConfid
4,4755,89,0,0,0,20.716974,0,18.454356,6.310461,0.795498,...,0,0,0.014691,0,0,1,1,0,0,XXXConfid


In [12]:
print("Missing values per column:\n", df.isnull().sum()[df.isnull().sum() > 0])
print("\nDiagnosis value counts:\n", df["Diagnosis"].value_counts())
print("\nColumns:\n", list(df.columns))

Missing values per column:
 Series([], dtype: int64)

Diagnosis value counts:
 Diagnosis
0    1389
1     760
Name: count, dtype: int64

Columns:
 ['PatientID', 'Age', 'Gender', 'Ethnicity', 'EducationLevel', 'BMI', 'Smoking', 'AlcoholConsumption', 'PhysicalActivity', 'DietQuality', 'SleepQuality', 'FamilyHistoryAlzheimers', 'CardiovascularDisease', 'Diabetes', 'Depression', 'HeadInjury', 'Hypertension', 'SystolicBP', 'DiastolicBP', 'CholesterolTotal', 'CholesterolLDL', 'CholesterolHDL', 'CholesterolTriglycerides', 'MMSE', 'FunctionalAssessment', 'MemoryComplaints', 'BehavioralProblems', 'ADL', 'Confusion', 'Disorientation', 'PersonalityChanges', 'DifficultyCompletingTasks', 'Forgetfulness', 'Diagnosis', 'DoctorInCharge']


In [14]:
#dropping unecessary columns


df_clean = df.drop(columns=["PatientID", "DoctorInCharge"])


X = df_clean.drop(columns=["Diagnosis"])
y = df_clean["Diagnosis"]

print("X shape:", X.shape)
print("y shape:", y.shape)
X.dtypes

X shape: (2149, 32)
y shape: (2149,)


Age                            int64
Gender                         int64
Ethnicity                      int64
EducationLevel                 int64
BMI                          float64
Smoking                        int64
AlcoholConsumption           float64
PhysicalActivity             float64
DietQuality                  float64
SleepQuality                 float64
FamilyHistoryAlzheimers        int64
CardiovascularDisease          int64
Diabetes                       int64
Depression                     int64
HeadInjury                     int64
Hypertension                   int64
SystolicBP                     int64
DiastolicBP                    int64
CholesterolTotal             float64
CholesterolLDL               float64
CholesterolHDL               float64
CholesterolTriglycerides     float64
MMSE                         float64
FunctionalAssessment         float64
MemoryComplaints               int64
BehavioralProblems             int64
ADL                          float64
C

In [17]:
Feature Engineering

SyntaxError: invalid syntax (2107749883.py, line 1)

In [18]:
X_fe = X.copy()

# Blood pressure: pulse pressure often carries more signal than either value alone
X_fe["PulsePressure"] = X_fe["SystolicBP"] - X_fe["DiastolicBP"]

# Cholesterol ratio: LDL/HDL is a standard cardiovascular risk indicator
X_fe["CholesterolRatio"] = X_fe["CholesterolLDL"] / X_fe["CholesterolHDL"]

# Symptom burden: sum of binary cognitive/behavioral symptom flags
symptom_cols = [
    "MemoryComplaints", "BehavioralProblems", "Confusion",
    "Disorientation", "PersonalityChanges",
    "DifficultyCompletingTasks", "Forgetfulness"
]
X_fe["SymptomCount"] = X_fe[symptom_cols].sum(axis=1)

# Comorbidity burden: sum of binary medical history flags
comorbidity_cols = [
    "FamilyHistoryAlzheimers", "CardiovascularDisease",
    "Diabetes", "Depression", "HeadInjury", "Hypertension"
]
X_fe["ComorbidityCount"] = X_fe[comorbidity_cols].sum(axis=1)

# Composite cognitive/functional decline score (MMSE and FunctionalAssessment/ADL
# are all scaled so that LOWER = more impaired, so we can combine them directly)
X_fe["CognitiveFunctionalScore"] = X_fe["MMSE"] + X_fe["FunctionalAssessment"] + X_fe["ADL"]

print("New shape:", X_fe.shape)
X_fe[["PulsePressure", "CholesterolRatio", "SymptomCount", "ComorbidityCount", "CognitiveFunctionalScore"]].describe()

New shape: (2149, 37)


,PulsePressure,CholesterolRatio,SymptomCount,ComorbidityCount,CognitiveFunctionalScore
count,2149.000000,2149.000000,2149.000000,2149.000000,2149.000000
mean,44.416938,2.539761,1.339228,0.989297,24.818145
std,31.312940,1.591293,1.016554,0.900743,9.674116
min,-28.000000,0.522917,0.000000,0.000000,2.545081
25%,22.000000,1.408996,1.000000,0.000000,16.990164
50%,45.000000,2.078159,1.000000,1.000000,24.733000
75%,67.000000,3.216513,2.000000,2.000000,32.645910
max,118.000000,9.446743,5.000000,5.000000,47.468764


In [23]:
X_fe

,Age,Gender,Ethnicity,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,DietQuality,SleepQuality,...,DifficultyCompletingTasks,Forgetfulness,PulsePressure,CholesterolRatio,SymptomCount,ComorbidityCount,CognitiveFunctionalScore,BPCategoryEncoded,GenderLabel,EthnicityLabel
0,73,0,0,2,22.927749,0,13.297218,6.327112,1.347214,9.025679,...,1,0,70,1.667061,1,2,29.708293,3,Male,Caucasian
1,89,0,0,0,26.827681,0,4.542524,7.619885,0.518767,7.151293,...,0,1,51,2.447320,1,0,30.324387,0,Male,Caucasian
2,73,0,3,1,17.795882,0,19.555085,7.844988,1.826335,9.673574,...,1,0,-17,2.197473,2,1,20.370874,3,Male,Other
3,74,1,0,1,33.800817,1,12.209266,8.428001,7.435604,8.392554,...,0,0,3,0.954850,1,0,29.437459,3,Female,Caucasian
4,89,0,0,0,20.716974,0,18.454356,6.310461,0.795498,5.597238,...,1,0,-23,1.632894,2,0,19.577339,3,Male,Caucasian
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2144,61,0,0,1,39.121757,0,1.561126,4.049964,6.555306,7.535540,...,0,0,21,1.556706,1,0,5.932695,3,Male,Caucasian
2145,75,0,0,2,17.857903,0,18.767261,1.360667,2.904662,8.555256,...,0,0,46,1.018804,1,0,24.350492,3,Male,Caucasian
2146,77,0,0,1,15.476479,0,4.594670,9.886002,8.120025,5.769464,...,0,0,-3,1.567718,0,0,24.019474,3,Male,Caucasian
2147,78,1,3,1,15.299911,0,8.674505,6.354282,1.263427,8.322874,...,0,1,7,0.645697,1,1,12.989781,3,Female,Other


In [20]:
#assing new column for bp categories

def bp_category(row):
    sys, dia = row["SystolicBP"], row["DiastolicBP"]
    
    if sys > 180 or dia > 120:
        return "Hypertensive Crisis"
    elif sys >= 140 or dia >= 90:
        return "Stage 2 Hypertension"
    elif sys >= 130 or dia >= 80:
        return "Stage 1 Hypertension"
    elif 120 <= sys <= 129 and dia < 80:
        return "Elevated"
    elif sys < 120 and dia < 80:
        return "Normal"
    else:
        
        return "Stage 1 Hypertension"

X_fe["BPCategory"] = X_fe.apply(bp_category, axis=1)
print(X_fe["BPCategory"].value_counts())

BPCategory
Stage 2 Hypertension    1557
Stage 1 Hypertension     275
Normal                   243
Elevated                  74
Name: count, dtype: int64


In [21]:
#encoding bp

bp_order = {
    "Normal": 0,
    "Elevated": 1,
    "Stage 1 Hypertension": 2,
    "Stage 2 Hypertension": 3,
    "Hypertensive Crisis": 4
}
X_fe["BPCategoryEncoded"] = X_fe["BPCategory"].map(bp_order)

# Drop the text version now that we have the encoded one, and drop the raw
# PulsePressure calc's redundant inputs is NOT needed — keep SystolicBP/DiastolicBP too,
# since the raw values still carry information the category buckets lose
X_fe = X_fe.drop(columns=["BPCategory"])

print("New shape:", X_fe.shape)
X_fe[["SystolicBP", "DiastolicBP", "BPCategoryEncoded"]].head(10)

New shape: (2149, 38)


,SystolicBP,DiastolicBP,BPCategoryEncoded
0,142,72,3
1,115,64,0
2,99,116,3
3,118,115,3
4,94,117,3
5,168,62,3
6,143,88,3
7,117,63,0
8,117,119,3
9,130,78,2


In [22]:
# Map numeric codes to readable labels first (for clarity and to catch mapping errors)
gender_map = {0: "Male", 1: "Female"}
ethnicity_map = {0: "Caucasian", 1: "African American", 2: "Asian", 3: "Other"}

X_fe["GenderLabel"] = X_fe["Gender"].map(gender_map)
X_fe["EthnicityLabel"] = X_fe["Ethnicity"].map(ethnicity_map)

print(X_fe["GenderLabel"].value_counts())
print(X_fe["EthnicityLabel"].value_counts())

GenderLabel
Female    1088
Male      1061
Name: count, dtype: int64
EthnicityLabel
Caucasian           1278
African American     454
Other                211
Asian                206
Name: count, dtype: int64


In [28]:
#one hot encoding ggender

X_fe = pd.get_dummies(
    X_fe,
    columns=["GenderLabel", "EthnicityLabel"],
    prefix=["Gender", "Ethnicity"],
    drop_first=True  
)

# Drop the original numeric-coded columns now that we have the one-hot versions
X_fe = X_fe.drop(columns=["Gender", "Ethnicity"])

print("New shape:", X_fe.shape)
X_fe.columns.tolist()

New shape: (2149, 43)


['Age',
 'EducationLevel',
 'BMI',
 'Smoking',
 'AlcoholConsumption',
 'PhysicalActivity',
 'DietQuality',
 'SleepQuality',
 'FamilyHistoryAlzheimers',
 'CardiovascularDisease',
 'Diabetes',
 'Depression',
 'HeadInjury',
 'Hypertension',
 'SystolicBP',
 'DiastolicBP',
 'CholesterolTotal',
 'CholesterolLDL',
 'CholesterolHDL',
 'CholesterolTriglycerides',
 'MMSE',
 'FunctionalAssessment',
 'MemoryComplaints',
 'BehavioralProblems',
 'ADL',
 'Confusion',
 'Disorientation',
 'PersonalityChanges',
 'DifficultyCompletingTasks',
 'Forgetfulness',
 'PulsePressure',
 'CholesterolRatio',
 'SymptomCount',
 'ComorbidityCount',
 'CognitiveFunctionalScore',
 'BPCategoryEncoded',
 'BMICategoryEncoded',
 'TotalCholCategory',
 'LDLCategory',
 'Gender_Male',
 'Ethnicity_Asian',
 'Ethnicity_Caucasian',
 'Ethnicity_Other']

In [31]:
X_fe

,Age,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,DietQuality,SleepQuality,FamilyHistoryAlzheimers,CardiovascularDisease,...,ComorbidityCount,CognitiveFunctionalScore,BPCategoryEncoded,BMICategoryEncoded,TotalCholCategory,LDLCategory,Gender_Male,Ethnicity_Asian,Ethnicity_Caucasian,Ethnicity_Other
0,73,2,22.927749,0,13.297218,6.327112,1.347214,9.025679,0,0,...,2,29.708293,3,1,2,0,True,False,True,False
1,89,0,26.827681,0,4.542524,7.619885,0.518767,7.151293,0,0,...,0,30.324387,0,2,1,4,True,False,True,False
2,73,1,17.795882,0,19.555085,7.844988,1.826335,9.673574,1,0,...,1,20.370874,3,0,2,2,True,False,False,True
3,74,1,33.800817,1,12.209266,8.428001,7.435604,8.392554,0,0,...,0,29.437459,3,3,0,0,False,False,True,False
4,89,0,20.716974,0,18.454356,6.310461,0.795498,5.597238,0,0,...,0,19.577339,3,1,1,0,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2144,61,1,39.121757,0,1.561126,4.049964,6.555306,7.535540,0,0,...,0,5.932695,3,4,2,0,True,False,True,False
2145,75,2,17.857903,0,18.767261,1.360667,2.904662,8.555256,0,0,...,0,24.350492,3,0,0,0,True,False,True,False
2146,77,1,15.476479,0,4.594670,9.886002,8.120025,5.769464,0,0,...,0,24.019474,3,0,1,2,True,False,True,False
2147,78,1,15.299911,0,8.674505,6.354282,1.263427,8.322874,0,1,...,1,12.989781,3,0,2,0,False,False,False,True


In [25]:
#ewncoding bmi

def bmi_category(bmi):
    if bmi < 18.5:
        return "Underweight"
    elif bmi < 25.0:
        return "Healthy"
    elif bmi < 30.0:
        return "Overweight"
    elif bmi < 35.0:
        return "Obese Class 1"
    elif bmi < 40.0:
        return "Obese Class 2"
    else:
        return "Obese Class 3"

X_fe["BMICategory"] = X_fe["BMI"].apply(bmi_category)
print(X_fe["BMICategory"].value_counts())

BMICategory
Healthy          544
Obese Class 2    441
Overweight       437
Obese Class 1    430
Underweight      297
Name: count, dtype: int64


In [26]:
bmi_order = {
    "Underweight": 0,
    "Healthy": 1,
    "Overweight": 2,
    "Obese Class 1": 3,
    "Obese Class 2": 4,
    "Obese Class 3": 5
}
X_fe["BMICategoryEncoded"] = X_fe["BMICategory"].map(bmi_order)
X_fe = X_fe.drop(columns=["BMICategory"])

print("New shape:", X_fe.shape)
X_fe[["BMI", "BMICategoryEncoded"]].head(10)

New shape: (2149, 41)


,BMI,BMICategoryEncoded
0,22.927749,1
1,26.827681,2
2,17.795882,0
3,33.800817,3
4,20.716974,1
5,30.626886,3
6,38.387622,4
7,18.776009,1
8,27.833188,2
9,35.456302,4


In [30]:
#categorizing cholestrol

def total_chol_category(val):
    if val < 200:
        return 0  # Desirable
    elif val < 240:
        return 1  # Borderline High
    else:
        return 2  # High

def ldl_category(val):
    if val < 100:
        return 0  # Optimal
    elif val < 130:
        return 1  # Near/Above optimal
    elif val < 160:
        return 2  # Borderline high
    elif val < 190:
        return 3  # High
    else:
        return 4  # Very high

def hdl_category(val, is_female):
    # Lower thresholds for men, higher for women
    low_cut = 50 if is_female else 40
    if val < low_cut:
        return 0  # Low risk / undesirable
    elif val <= 80:
        return 1  # Normal / acceptable 
    else:
        return 2  # High (above 80)

def triglyceride_category(val):
    if val < 150:
        return 0  # Normal
    elif val < 200:
        return 1  # Borderline high
    elif val < 500:
        return 2  # High
    else:
        return 3  # Very high

X_fe["TotalCholCategory"] = X_fe["CholesterolTotal"].apply(total_chol_category)
X_fe["LDLCategory"] = X_fe["CholesterolLDL"].apply(ldl_category)
X_fe["HDLCategory"] = X_fe.apply(lambda row: hdl_category(row["CholesterolHDL"], row["Gender_Female"] == 1), axis=1)
X_fe["TriglycerideCategory"] = X_fe["CholesterolTriglycerides"].apply(triglyceride_category)

print(X_fe[["TotalCholCategory", "LDLCategory", "HDLCategory", "TriglycerideCategory"]].apply(pd.Series.value_counts))

KeyError: 'Gender_Female'

In [32]:
print([col for col in X_fe.columns if "Gender" in col])

['Gender_Male']


In [33]:
X_fe["HDLCategory"] = X_fe.apply(
    lambda row: hdl_category(row["CholesterolHDL"], row["Gender_Male"] == 0), axis=1
)
X_fe["TriglycerideCategory"] = X_fe["CholesterolTriglycerides"].apply(triglyceride_category)

print(X_fe[["TotalCholCategory", "LDLCategory", "HDLCategory", "TriglycerideCategory"]].apply(pd.Series.value_counts))

   TotalCholCategory  LDLCategory  HDLCategory  TriglycerideCategory
0              698.0          734        698.0                 606.0
1              600.0          439        942.0                 282.0
2              851.0          415        509.0                1261.0
3                NaN          412          NaN                   NaN
4                NaN          149          NaN                   NaN


In [34]:
X_fe

,Age,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,DietQuality,SleepQuality,FamilyHistoryAlzheimers,CardiovascularDisease,...,BPCategoryEncoded,BMICategoryEncoded,TotalCholCategory,LDLCategory,Gender_Male,Ethnicity_Asian,Ethnicity_Caucasian,Ethnicity_Other,HDLCategory,TriglycerideCategory
0,73,2,22.927749,0,13.297218,6.327112,1.347214,9.025679,0,0,...,3,1,2,0,True,False,True,False,0,1
1,89,0,26.827681,0,4.542524,7.619885,0.518767,7.151293,0,0,...,0,2,1,4,True,False,True,False,1,2
2,73,1,17.795882,0,19.555085,7.844988,1.826335,9.673574,1,0,...,3,0,2,2,True,False,False,True,1,0
3,74,1,33.800817,1,12.209266,8.428001,7.435604,8.392554,0,0,...,3,3,0,0,False,False,True,False,1,2
4,89,0,20.716974,0,18.454356,6.310461,0.795498,5.597238,0,0,...,3,1,1,0,True,False,True,False,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2144,61,1,39.121757,0,1.561126,4.049964,6.555306,7.535540,0,0,...,3,4,2,0,True,False,True,False,1,2
2145,75,2,17.857903,0,18.767261,1.360667,2.904662,8.555256,0,0,...,3,0,0,0,True,False,True,False,2,2
2146,77,1,15.476479,0,4.594670,9.886002,8.120025,5.769464,0,0,...,3,0,1,2,True,False,True,False,2,2
2147,78,1,15.299911,0,8.674505,6.354282,1.263427,8.322874,0,1,...,3,0,2,0,False,False,False,True,2,0


In [35]:
print("Final shape:", X_fe.shape)
print("\nAll columns:\n", X_fe.columns.tolist())

Final shape: (2149, 45)

All columns:
 ['Age', 'EducationLevel', 'BMI', 'Smoking', 'AlcoholConsumption', 'PhysicalActivity', 'DietQuality', 'SleepQuality', 'FamilyHistoryAlzheimers', 'CardiovascularDisease', 'Diabetes', 'Depression', 'HeadInjury', 'Hypertension', 'SystolicBP', 'DiastolicBP', 'CholesterolTotal', 'CholesterolLDL', 'CholesterolHDL', 'CholesterolTriglycerides', 'MMSE', 'FunctionalAssessment', 'MemoryComplaints', 'BehavioralProblems', 'ADL', 'Confusion', 'Disorientation', 'PersonalityChanges', 'DifficultyCompletingTasks', 'Forgetfulness', 'PulsePressure', 'CholesterolRatio', 'SymptomCount', 'ComorbidityCount', 'CognitiveFunctionalScore', 'BPCategoryEncoded', 'BMICategoryEncoded', 'TotalCholCategory', 'LDLCategory', 'Gender_Male', 'Ethnicity_Asian', 'Ethnicity_Caucasian', 'Ethnicity_Other', 'HDLCategory', 'TriglycerideCategory']


In [37]:
#Train/test split


from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_fe, y, test_size=0.2, random_state=42, stratify=y
)

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)

Train shape: (1719, 45)
Test shape: (430, 45)


In [38]:
#Featue Scaling

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)  
X_test_scaled = scaler.transform(X_test)          

print("Scaled train shape:", X_train_scaled.shape)
print("Scaled test shape:", X_test_scaled.shape)

Scaled train shape: (1719, 45)
Scaled test shape: (430, 45)


In [39]:
#fit_transform on train vs just transform on test — that asymmetry is the whole point, it's what prevents the leakage.

In [40]:
#Random forest

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    class_weight="balanced"  # compensating for class imbalance
)



In [41]:
rf_model.fit(X_train_scaled, y_train)


,n_estimators,300
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [42]:
#random forest metrics
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, classification_report, confusion_matrix
)

preds = rf_model.predict(X_test_scaled)
probs = rf_model.predict_proba(X_test_scaled)[:, 1]

print("Accuracy:", accuracy_score(y_test, preds))
print("Precision:", precision_score(y_test, preds))
print("Recall:", recall_score(y_test, preds))
print("F1 Score:", f1_score(y_test, preds))
print("ROC-AUC:", roc_auc_score(y_test, probs))

print("\nClassification Report:\n", classification_report(y_test, preds))
print("Confusion Matrix:\n", confusion_matrix(y_test, preds))

Accuracy: 0.9325581395348838
Precision: 0.9424460431654677
Recall: 0.8618421052631579
F1 Score: 0.9003436426116839
ROC-AUC: 0.9439487883377508

Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.97      0.95       278
           1       0.94      0.86      0.90       152

    accuracy                           0.93       430
   macro avg       0.94      0.92      0.92       430
weighted avg       0.93      0.93      0.93       430

Confusion Matrix:
 [[270   8]
 [ 21 131]]


In [43]:
#21 real AD patients (out of 152) got predicted as "No AD."
#We need tro reduce that number

In [44]:
#cchecking feature importance

importances = pd.Series(rf_model.feature_importances_, index=X_fe.columns)
importances_sorted = importances.sort_values(ascending=False)

print(importances_sorted.head(15))

FunctionalAssessment        0.151842
ADL                         0.134856
CognitiveFunctionalScore    0.106063
MMSE                        0.088355
MemoryComplaints            0.073165
BehavioralProblems          0.040553
DietQuality                 0.024201
CholesterolTriglycerides    0.024048
PhysicalActivity            0.023436
SleepQuality                0.023239
CholesterolHDL              0.022958
BMI                         0.022242
AlcoholConsumption          0.021666
SymptomCount                0.021586
CholesterolTotal            0.021468
dtype: float64


FunctionalAssessment (15.2%), ADL (13.5%), MMSE (8.8%) — the three top  scores dominate.
which is how Alzheimer's is actually diagnosed in practice.

Our engineered CognitiveFunctionalScore (10.6%) ranks 3rd — it's clearly capturing real signal, not just noise

MemoryComplaints (7.3%) and BehavioralProblems (4.1%) — are contributing too but leass than objecticeve assessments

evrything blow that are very minor coonstributors

none of our other engineered features (SymptomCount did make it at 2.2%, but PulsePressure, ComorbidityCount, BPCategoryEncoded, BMICategoryEncoded, the cholesterol categories, Gender/Ethnicity) show up. They are most likely contributing very  little.
We could most likely prune these


In [45]:
#Train vs trest performance

train_preds = rf_model.predict(X_train_scaled)
train_probs = rf_model.predict_proba(X_train_scaled)[:, 1]

print("=== TRAIN performance ===")
print("Accuracy:", accuracy_score(y_train, train_preds))
print("ROC-AUC:", roc_auc_score(y_train, train_probs))

print("\n=== TEST performance (for comparison) ===")
print("Accuracy:", accuracy_score(y_test, preds))
print("ROC-AUC:", roc_auc_score(y_test, probs)) 

=== TRAIN performance ===
Accuracy: 1.0
ROC-AUC: 1.0

=== TEST performance (for comparison) ===
Accuracy: 0.9325581395348838
ROC-AUC: 0.9439487883377508


In [ ]:
#model is over fitting


In [46]:
# adding constraints



rf_model_v2 = RandomForestClassifier(
    n_estimators=300,
    max_depth=8,            
    min_samples_leaf=5,     
    min_samples_split=10,   
    random_state=42,
    class_weight="balanced"
)



In [47]:
rf_model_v2.fit(X_train_scaled, y_train)



,n_estimators,300
,criterion,'gini'
,max_depth,8
,min_samples_split,10
,min_samples_leaf,5
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [48]:
train_preds_v2 = rf_model_v2.predict(X_train_scaled)
test_preds_v2 = rf_model_v2.predict(X_test_scaled)
test_probs_v2 = rf_model_v2.predict_proba(X_test_scaled)[:, 1]

print("=== TRAIN (v2) ===")
print("Accuracy:", accuracy_score(y_train, train_preds_v2))

print("\n=== TEST (v2) ===")
print("Accuracy:", accuracy_score(y_test, test_preds_v2))
print("ROC-AUC:", roc_auc_score(y_test, test_probs_v2))
print(classification_report(y_test, test_preds_v2))

=== TRAIN (v2) ===
Accuracy: 0.9674229203025014

=== TEST (v2) ===
Accuracy: 0.9348837209302325
ROC-AUC: 0.9421857251041273
              precision    recall  f1-score   support

           0       0.93      0.97      0.95       278
           1       0.94      0.88      0.90       152

    accuracy                           0.93       430
   macro avg       0.94      0.92      0.93       430
weighted avg       0.93      0.93      0.93       430



In [ ]:
#The gap between train and test has nearly halved without compromising test performance

In [49]:
#tuning hyperparameters with gridSearchCV

from sklearn.model_selection import GridSearchCV

param_grid = {
    "max_depth": [4, 6, 8, 10],
    "min_samples_leaf": [5, 10, 15, 20],
    "min_samples_split": [10, 20, 30],
    "n_estimators": [200, 300]
}

rf_base = RandomForestClassifier(random_state=42, class_weight="balanced")

grid_search = GridSearchCV(
    estimator=rf_base,
    param_grid=param_grid,
    cv=5,                    
    scoring="roc_auc",       
    n_jobs=-1,               
    verbose=1
)



In [50]:
grid_search.fit(X_train_scaled, y_train)

Fitting 5 folds for each of 96 candidates, totalling 480 fits


,estimator,RandomForestC...ndom_state=42)
,param_grid,"{'max_depth': [4, 6, ...], 'min_samples_leaf': [5, 10, ...], 'min_samples_split': [10, 20, ...], 'n_estimators': [200, 300]}"
,scoring,'roc_auc'
,n_jobs,-1
,refit,True
,cv,5
,verbose,1
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,n_estimators,300


In [51]:
print("Best parameters:", grid_search.best_params_)
print("Best CV ROC-AUC:", grid_search.best_score_)

Best parameters: {'max_depth': 10, 'min_samples_leaf': 5, 'min_samples_split': 30, 'n_estimators': 300}
Best CV ROC-AUC: 0.9496158332086904


In [52]:
best_rf = grid_search.best_estimator_

train_preds_best = best_rf.predict(X_train_scaled)
test_preds_best = best_rf.predict(X_test_scaled)
test_probs_best = best_rf.predict_proba(X_test_scaled)[:, 1]

print("=== TRAIN (tuned) ===")
print("Accuracy:", accuracy_score(y_train, train_preds_best))

print("\n=== TEST (tuned) ===")
print("Accuracy:", accuracy_score(y_test, test_preds_best))
print("ROC-AUC:", roc_auc_score(y_test, test_probs_best))
print(classification_report(y_test, test_preds_best))

=== TRAIN (tuned) ===
Accuracy: 0.9645142524723677

=== TEST (tuned) ===
Accuracy: 0.9395348837209302
ROC-AUC: 0.9424697084437712
              precision    recall  f1-score   support

           0       0.94      0.96      0.95       278
           1       0.93      0.89      0.91       152

    accuracy                           0.94       430
   macro avg       0.94      0.93      0.93       430
weighted avg       0.94      0.94      0.94       430



In [53]:
print(grid_search.best_params_)

{'max_depth': 10, 'min_samples_leaf': 5, 'min_samples_split': 30, 'n_estimators': 300}


we've managed tto meaningfully close the overfitting gap without giving up any test performance. 
this a solid stopping point for Random Forest

we're already at a healthy 2.5-point train/test gap with pretty good test performance, 
I'd say this is a reasonable place to stop tuning rather than chase miniscule gains.

In [ ]:
#Testing with Logistic Regression

In [54]:
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(max_iter=1000, random_state=42, class_weight="balanced")


In [56]:
lr_model.fit(X_train_scaled, y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,'balanced'
,random_state,42
,solver,'lbfgs'
,max_iter,1000
,multi_class,'deprecated'


In [57]:
train_preds_lr = lr_model.predict(X_train_scaled)
test_preds_lr = lr_model.predict(X_test_scaled)
test_probs_lr = lr_model.predict_proba(X_test_scaled)[:, 1]

In [58]:
print("=== TRAIN (Logistic Regression) ===")
print("Accuracy:", accuracy_score(y_train, train_preds_lr))

print("\n=== TEST (Logistic Regression) ===")
print("Accuracy:", accuracy_score(y_test, test_preds_lr))
print("ROC-AUC:", roc_auc_score(y_test, test_probs_lr))
print(classification_report(y_test, test_preds_lr))

=== TRAIN (Logistic Regression) ===
Accuracy: 0.840023269342641

=== TEST (Logistic Regression) ===
Accuracy: 0.8116279069767441
ROC-AUC: 0.8823599015524423
              precision    recall  f1-score   support

           0       0.91      0.79      0.84       278
           1       0.69      0.86      0.76       152

    accuracy                           0.81       430
   macro avg       0.80      0.82      0.80       430
weighted avg       0.83      0.81      0.82       430



In [ ]:
#Teswting with XGBoost

In [59]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=300,
    max_depth=4,           # keep shallow from the start, avoid v1's overfitting mistake
    learning_rate=0.1,
    eval_metric="logloss",
    random_state=42
)

In [60]:
xgb_model.fit(X_train_scaled, y_train)

,objective,'binary:logistic'
,base_score,None
,booster,None
,callbacks,None
,colsample_bylevel,None
,colsample_bynode,None
,colsample_bytree,None
,device,None
,early_stopping_rounds,None
,enable_categorical,True
,eval_metric,'logloss'


In [61]:
train_preds_xgb = xgb_model.predict(X_train_scaled)
test_preds_xgb = xgb_model.predict(X_test_scaled)
test_probs_xgb = xgb_model.predict_proba(X_test_scaled)[:, 1]

In [62]:
print("=== TRAIN (XGBoost) ===")
print("Accuracy:", accuracy_score(y_train, train_preds_xgb))

print("\n=== TEST (XGBoost) ===")
print("Accuracy:", accuracy_score(y_test, test_preds_xgb))
print("ROC-AUC:", roc_auc_score(y_test, test_probs_xgb))
print(classification_report(y_test, test_preds_xgb))

=== TRAIN (XGBoost) ===
Accuracy: 1.0

=== TEST (XGBoost) ===
Accuracy: 0.9441860465116279
ROC-AUC: 0.9434399848542219
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       278
           1       0.94      0.90      0.92       152

    accuracy                           0.94       430
   macro avg       0.94      0.93      0.94       430
weighted avg       0.94      0.94      0.94       430



In [64]:
#XGB  Regularization

In [65]:
xgb_model_v2 = XGBClassifier(
    n_estimators=300,
    max_depth=3,           # decreasing depth by 1
    learning_rate=0.05,    # dereased learning, overfit per-tree  il  reduced
    subsample=0.8,         # each tree sees only 80% of rows (adds randomness)
    colsample_bytree=0.8,  # each tree sees only 80% of features
    reg_lambda=2.0,         # L2 regularization
    eval_metric="logloss",
    random_state=42
)

In [66]:
xgb_model_v2.fit(X_train_scaled, y_train)

,objective,'binary:logistic'
,base_score,None
,booster,None
,callbacks,None
,colsample_bylevel,None
,colsample_bynode,None
,colsample_bytree,0.8
,device,None
,early_stopping_rounds,None
,enable_categorical,True
,eval_metric,'logloss'


In [67]:
train_preds_xgb2 = xgb_model_v2.predict(X_train_scaled)
test_preds_xgb2 = xgb_model_v2.predict(X_test_scaled)
test_probs_xgb2 = xgb_model_v2.predict_proba(X_test_scaled)[:, 1]

In [68]:
print("=== TRAIN (XGBoost v2) ===")
print("Accuracy:", accuracy_score(y_train, train_preds_xgb2))

print("\n=== TEST (XGBoost v2) ===")
print("Accuracy:", accuracy_score(y_test, test_preds_xgb2))
print("ROC-AUC:", roc_auc_score(y_test, test_probs_xgb2))
print(classification_report(y_test, test_preds_xgb2))

=== TRAIN (XGBoost v2) ===
Accuracy: 0.9714950552646888

=== TEST (XGBoost v2) ===
Accuracy: 0.9441860465116279
ROC-AUC: 0.9447889057175313
              precision    recall  f1-score   support

           0       0.96      0.96      0.96       278
           1       0.92      0.92      0.92       152

    accuracy                           0.94       430
   macro avg       0.94      0.94      0.94       430
weighted avg       0.94      0.94      0.94       430



In [69]:
#checking class weights needed to
neg, pos = (y_train == 0).sum(), (y_train == 1).sum()
scale = neg / pos
print("Suggested scale_pos_weight:", scale)

Suggested scale_pos_weight: 1.8273026315789473


In [70]:
#using RandomizedSearchCVto figure out best hyperparameters
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import uniform, randint

param_dist = {
    "n_estimators": randint(100, 500),
    "max_depth": randint(2, 6),
    "learning_rate": uniform(0.01, 0.19),      # 0.01 to 0.2
    "subsample": uniform(0.6, 0.4),             # 0.6 to 1.0
    "colsample_bytree": uniform(0.6, 0.4),      # 0.6 to 1.0
    "reg_lambda": uniform(0.5, 4.5),            # 0.5 to 5.0
    "scale_pos_weight": [1, scale]              # test both unweighted and balanced
}

In [71]:
xgb_base = XGBClassifier(eval_metric="logloss", random_state=42)

In [72]:

random_search = RandomizedSearchCV(
    estimator=xgb_base,
    param_distributions=param_dist,
    n_iter=50,              
    cv=5,
    scoring="roc_auc",
    n_jobs=-1,
    random_state=42,
    verbose=1
)

In [73]:
random_search.fit(X_train_scaled, y_train)

Fitting 5 folds for each of 50 candidates, totalling 250 fits


,estimator,"XGBClassifier...ree=None, ...)"
,param_distributions,"{'colsample_bytree': <scipy.stats....0019FA61C7C50>, 'learning_rate': <scipy.stats....0019FA61FD940>, 'max_depth': <scipy.stats....0019FA61C7750>, 'n_estimators': <scipy.stats....0019FA61FD7F0>, ...}"
,n_iter,50
,scoring,'roc_auc'
,n_jobs,-1
,refit,True
,cv,5
,verbose,1
,pre_dispatch,'2*n_jobs'
,random_state,42
,error_score,nan


In [74]:
print("Best params:", random_search.best_params_)
print("Best CV ROC-AUC:", random_search.best_score_)

Best params: {'colsample_bytree': np.float64(0.8809936335948436), 'learning_rate': np.float64(0.07830331873175347), 'max_depth': 2, 'n_estimators': 269, 'reg_lambda': np.float64(4.142125199653311), 'scale_pos_weight': 1, 'subsample': np.float64(0.7024827774377832)}
Best CV ROC-AUC: 0.9550694570526425


In [75]:
print("Number of fits completed:", len(random_search.cv_results_["mean_test_score"]))

Number of fits completed: 50


In [76]:
best_xgb = random_search.best_estimator_

train_preds_final = best_xgb.predict(X_train_scaled)
test_preds_final = best_xgb.predict(X_test_scaled)
test_probs_final = best_xgb.predict_proba(X_test_scaled)[:, 1]

print("=== TRAIN (final XGBoost) ===")
print("Accuracy:", accuracy_score(y_train, train_preds_final))

print("\n=== TEST (final XGBoost) ===")
print("Accuracy:", accuracy_score(y_test, test_preds_final))
print("ROC-AUC:", roc_auc_score(y_test, test_probs_final))
print(classification_report(y_test, test_preds_final))

=== TRAIN (final XGBoost) ===
Accuracy: 0.9604421175101804

=== TEST (final XGBoost) ===
Accuracy: 0.9465116279069767
ROC-AUC: 0.9425170390003788
              precision    recall  f1-score   support

           0       0.95      0.96      0.96       278
           1       0.93      0.91      0.92       152

    accuracy                           0.95       430
   macro avg       0.94      0.94      0.94       430
weighted avg       0.95      0.95      0.95       430



In [77]:
#cross validation

from sklearn.model_selection import cross_val_score
import numpy as np

cv_scores = cross_val_score(
    best_xgb, X_fe, y,
    cv=10,
    scoring="roc_auc",
    n_jobs=-1
)

print("Individual fold scores:", cv_scores)
print("Mean ROC-AUC:", cv_scores.mean())
print("Std Dev:", cv_scores.std())

Individual fold scores: [0.99432033 0.99450966 0.99876941 0.99252177 0.98968194 0.99394169
 1.         0.99223779 0.95768648 0.58257056]
Mean ROC-AUC: 0.9496239621575052
Std Dev: 0.1228753759368796


In [78]:
 #a single fold score is a t 0,58 while most are above 0.9
#most likely caused by lack of suffling

SyntaxError: invalid syntax (4215075954.py, line 1)

In [79]:
#Shuffling

from sklearn.model_selection import StratifiedKFold, cross_val_score

cv_shuffled = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

cv_scores_shuffled = cross_val_score(
    best_xgb, X_fe, y,
    cv=cv_shuffled,
    scoring="roc_auc",
    n_jobs=-1
)

print("Individual fold scores:", cv_scores_shuffled)
print("Mean ROC-AUC:", cv_scores_shuffled.mean())
print("Std Dev:", cv_scores_shuffled.std())

Individual fold scores: [0.95513063 0.95390004 0.95513063 0.95920106 0.94481257 0.92767891
 0.95588792 0.94926164 0.96961378 0.951373  ]
Mean ROC-AUC: 0.9521990188169831
Std Dev: 0.010252310098791536


In [80]:
#our model's true performance is consistent around 0.95 ROC-AUC

In [81]:
# threshold tuning

from sklearn.metrics import precision_recall_curve
import numpy as np

precisions, recalls, thresholds = precision_recall_curve(y_test, test_probs_final)

# Printing a sample of threshold/precision/recall combos
for t in np.arange(0.2, 0.6, 0.05):
    idx = np.argmin(np.abs(thresholds - t))
    print(f"Threshold: {t:.2f} | Precision: {precisions[idx]:.3f} | Recall: {recalls[idx]:.3f}")

Threshold: 0.20 | Precision: 0.797 | Recall: 0.928
Threshold: 0.25 | Precision: 0.844 | Recall: 0.928
Threshold: 0.30 | Precision: 0.892 | Recall: 0.928
Threshold: 0.35 | Precision: 0.904 | Recall: 0.928
Threshold: 0.40 | Precision: 0.916 | Recall: 0.928
Threshold: 0.45 | Precision: 0.927 | Recall: 0.921
Threshold: 0.50 | Precision: 0.933 | Recall: 0.921
Threshold: 0.55 | Precision: 0.946 | Recall: 0.914


In [83]:
custom_threshold = 0.40
test_preds_custom = (test_probs_final >= custom_threshold).astype(int)

print(f"=== TEST @ threshold {custom_threshold} ===")
print("Accuracy:", accuracy_score(y_test, test_preds_custom))
print(classification_report(y_test, test_preds_custom))
print("Confusion Matrix:\n", confusion_matrix(y_test, test_preds_custom))

=== TEST @ threshold 0.4 ===
Accuracy: 0.9441860465116279
              precision    recall  f1-score   support

           0       0.96      0.95      0.96       278
           1       0.92      0.93      0.92       152

    accuracy                           0.94       430
   macro avg       0.94      0.94      0.94       430
weighted avg       0.94      0.94      0.94       430

Confusion Matrix:
 [[265  13]
 [ 11 141]]


In [ ]:
#Moving to threshold 0.40 caught more real AD cases 
#false negatives went from ~14 down to 11
#false positives went up by about 4, but this should be ok since a false negative  is a much costlier mistake in this situation

In [84]:
Feature pruning
checking xg boosdt's featuere importances


SyntaxError: unterminated string literal (detected at line 2) (540967562.py, line 2)

In [85]:
importances_xgb = pd.Series(best_xgb.feature_importances_, index=X_fe.columns)
importances_xgb_sorted = importances_xgb.sort_values(ascending=False)

print(importances_xgb_sorted)

FunctionalAssessment         0.118668
ADL                          0.108651
MemoryComplaints             0.098985
CognitiveFunctionalScore     0.088568
MMSE                         0.086033
BehavioralProblems           0.073623
SymptomCount                 0.022911
Hypertension                 0.021745
Age                          0.020958
CholesterolTotal             0.020366
AlcoholConsumption           0.019109
CholesterolHDL               0.018552
ComorbidityCount             0.018456
SleepQuality                 0.018427
BPCategoryEncoded            0.018338
CardiovascularDisease        0.018010
PulsePressure                0.017888
PhysicalActivity             0.017686
CholesterolLDL               0.017306
CholesterolTriglycerides     0.017294
DietQuality                  0.017092
EducationLevel               0.016846
BMI                          0.016755
CholesterolRatio             0.016627
SystolicBP                   0.014637
DiastolicBP                  0.012954
Ethnicity_As

In [ ]:
13 features have exactly 0.000000 importance
all four of our bucketed cholesterol categories (Total/HDL/LDL/Triglyceride) and BMICategoryEncoded contribute nothing

the raw continuous values (CholesterolTotal, BMI, etc.) already capture what the model needs
we can just go bac k to the raw values



In [ ]:
#dropping features without importance

In [86]:
zero_importance_features = importances_xgb_sorted[importances_xgb_sorted == 0].index.tolist()
print("Dropping:", zero_importance_features)

X_pruned = X_fe.drop(columns=zero_importance_features)
print("New shape:", X_pruned.shape)

# Re-split and scale on pruned features
X_train_p, X_test_p, y_train_p, y_test_p = train_test_split(
    X_pruned, y, test_size=0.2, random_state=42, stratify=y
)

scaler_p = StandardScaler()
X_train_p_scaled = scaler_p.fit_transform(X_train_p)
X_test_p_scaled = scaler_p.transform(X_test_p)



Dropping: ['Ethnicity_Caucasian', 'TotalCholCategory', 'HDLCategory', 'LDLCategory', 'PersonalityChanges', 'BMICategoryEncoded', 'DifficultyCompletingTasks', 'Diabetes', 'Disorientation', 'HeadInjury', 'Depression', 'TriglycerideCategory']
New shape: (2149, 33)


In [87]:
# Retrain XGBoost with the same tuned hyperparameters
xgb_pruned = XGBClassifier(**random_search.best_params_, eval_metric="logloss", random_state=42)
xgb_pruned.fit(X_train_p_scaled, y_train_p)

test_preds_pruned = xgb_pruned.predict(X_test_p_scaled)
test_probs_pruned = xgb_pruned.predict_proba(X_test_p_scaled)[:, 1]

print("\n=== TEST (pruned features) ===")
print("Accuracy:", accuracy_score(y_test_p, test_preds_pruned))
print("ROC-AUC:", roc_auc_score(y_test_p, test_probs_pruned))
print(classification_report(y_test_p, test_preds_pruned))


=== TEST (pruned features) ===
Accuracy: 0.9511627906976744
ROC-AUC: 0.9432269973494889
              precision    recall  f1-score   support

           0       0.96      0.97      0.96       278
           1       0.94      0.92      0.93       152

    accuracy                           0.95       430
   macro avg       0.95      0.94      0.95       430
weighted avg       0.95      0.95      0.95       430



In [ ]:
Dropping the 12 dead-weight features improved accuracy and precision slightly 
while keeping ROC-AUC and recall unchanged



In [88]:
#Saving model

import joblib
import json

joblib.dump(xgb_pruned, "model.joblib")
joblib.dump(scaler_p, "scaler.joblib")



['scaler.joblib']

In [89]:
# Save the exact list and order of features the model expects
final_features = X_pruned.columns.tolist()
with open("feature_list.json", "w") as f:
    json.dump(final_features, f, indent=2)

print("Saved model.joblib, scaler.joblib, feature_list.json")
print("Final feature count:", len(final_features))
print(final_features)

Saved model.joblib, scaler.joblib, feature_list.json
Final feature count: 33
['Age', 'EducationLevel', 'BMI', 'Smoking', 'AlcoholConsumption', 'PhysicalActivity', 'DietQuality', 'SleepQuality', 'FamilyHistoryAlzheimers', 'CardiovascularDisease', 'Hypertension', 'SystolicBP', 'DiastolicBP', 'CholesterolTotal', 'CholesterolLDL', 'CholesterolHDL', 'CholesterolTriglycerides', 'MMSE', 'FunctionalAssessment', 'MemoryComplaints', 'BehavioralProblems', 'ADL', 'Confusion', 'Forgetfulness', 'PulsePressure', 'CholesterolRatio', 'SymptomCount', 'ComorbidityCount', 'CognitiveFunctionalScore', 'BPCategoryEncoded', 'Gender_Male', 'Ethnicity_Asian', 'Ethnicity_Other']


In [91]:
   import joblib, json
   joblib.dump(xgb_pruned, "model.joblib")
   joblib.dump(scaler_p, "scaler.joblib")
   with open("feature_list.json", "w") as f:
       json.dump(X_pruned.columns.tolist(), f, indent=2)